spring.application.name=OTPTelegramBotMIFI

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/otp_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:13d3791semenek}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

jwt.secret=${JWT_SECRET:bXktc3VwZXItc2VjcmV0LWtleS10aGF0LWlzLWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmchIQ==}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

email.username=${EMAIL_USERNAME:otp@otp-service.local}
email.password=${EMAIL_PASSWORD:}
email.from=${EMAIL_FROM:otp@otp-service.local}
mail.smtp.host=${SMTP_HOST:localhost}
mail.smtp.port=${SMTP_PORT:1025}
mail.smtp.auth=${SMTP_AUTH:false}
mail.smtp.starttls.enable=${SMTP_STARTTLS:false}

smpp.host=${SMPP_HOST:localhost}
smpp.port=${SMPP_PORT:2775}
smpp.system_id=${SMPP_SYSTEM_ID:smppclient1}
smpp.password=${SMPP_PASSWORD:password}
smpp.system_type=${SMPP_SYSTEM_TYPE:OTP}
smpp.source_addr=${SMPP_SOURCE_ADDR:OTPService}

telegram.bot.token=${8741444654:AAHHWL20kpZ9AqtcSwuj45_KCfdHUWyqa0U}

otp.expiration.check-interval-ms=60000

logging.level.com.jtt=DEBUG
logging.level.org.springframework.security=INFO
